Flow:
    Input Paths:
        - data/Earth - Dry Mud/Sample 0.png
        - data/Earth - Dry Mud/Sample 1.png
        - data/Earth - Dry Mud/Sample 2.png
        - data/Earth - Dry Mud/Sample 3.png
        - data/Earth - Dry Mud/Sample 4.png
        - data/Fabric - SP 1 Cap/Sample 5.png
        - data/Fabric - SP 1 Cap/Sample 6.png
        - data/Fabric - SP 1 Cap/Sample 7.png
        - data/Fabric - SP 1 Cap/Sample 8.png
        - data/Fabric - SP 1 Cap/Sample 9.png
    Output Path: results/album.png
    Output Size: [1024, 1024]
    Overlap: 20

Network: configs/network.yaml

SVBRDF:
    Type: Disney

Lights:
    - Type: Punctual
      Position: [0, 0, 0.25]
      Lumens: [0.5, 0.5, 0.5]

Viewer:
    Type: Perspective
    Position: [0, 0, 2]

Camera:
    Type: Perspective
    Position: [0, 0, 2]
    Direction: [0, 0, -1]
    Field of View: [64, 36]
    Resolution: [1280, 720]
    Exposure: 1
