Flow:
    Input Paths:
        - data/Earth - Dry Mud/Sample 0.png
        - data/Earth - Dry Mud/Sample 1.png
    Output Path: results/merge.png
    Overlap: 6

Network: configs/network.yaml

SVBRDF:
    Type: Disney

Lights:
    - Type: Punctual
      Position: [0, 0, 0.25]
      Lumens: [0.5, 0.5, 0.5]

Viewer:
    Type: Perspective
    Position: [0, 0, 2]

Camera:
    Type: Perspective
    Position: [0, 0, 1.5]
    Direction: [0, 0, -1]
    Field of View: [64, 36]
    Resolution: [1280, 720]
    Exposure: 1
