Flow:
    Input Paths:
        - data/Earth - Dry Mud/Sample 0.png
        - data/Earth - Dry Mud/Sample 1.png
    Output Path: results/morph.png
    Between: 2

Network: configs/network.yaml

SVBRDF:
    Type: Disney

Lights:
    - Type: Punctual
      Position: [0, 0, 2]
      Lumens: [8, 8, 8]

Viewer:
    Type: Perspective
    Position: [0, 0, 2]

Camera:
    Type: Perspective
    Position: [0, 0, 2]
    Direction: [0, 0, -1]
    Field of View: [64, 36]
    Resolution: [1280, 720]
    Exposure: 1