Flow:
    Input Path: data/Earth - Dry Mud/Sample 0.png
    Output Path: results/relight.png

Network: configs/network.yaml

SVBRDF:
    Type: Disney

Lights:
    - Type: Punctual
      Position: [0, 0, 0.25]
      Lumens: [0.5, 0.5, 0.5]

Viewer:
    Type: Perspective
    Position: [-0.1, -0.2, 0.5]

Camera:
    Type: Perspective
    Position: [-1.3, -0.8, 1.2]
    Direction: [1.5, 1.0, -1.6]
    Field of View: [64, 36]
    Resolution: [1280, 720]
    Exposure: 1
