Flow:
    Experiment: Final Model
    Epochs: 210
    Cycles: 1000
    Samples: 8
    Tuning: False
    Frequencies:
        Tests Publication: 200
        Image Publication: 200
        Parameter Checkpoint: 1000
        Early Stopping: 1000000
    Early Stopping:
        Epsilon: 0.0001
        Patience: 5
    Loss Weights:
        Diversity:
            Content: 0
            Style: 0
        Reconstruction:
            Content: 400
            Style: 0.5
            Texel: 400

Optimizer:
    Type: Adam
    Learning Rate: 0.0002
    Betas: [0.9, 0.999]
    Weight Decay: 0

SVBRDF:
    Type: Disney

Dataset: configs/dataset.yaml
Network: configs/network.yaml